
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class fr2 extends javax.swing.JFrame{

   int nrow1=2;
  
   FileOutputStream fin1 = null;
  File file = new File("data/new/param.txt");
  
  
       
   
public void setpara()
{	    //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//int row = jTable1.getSelectedRow();
//int column = jTable1.getSelectedColumn();
//System.out.println(row+""+column);
//Object value2 =  model.getValueAt(row , column);
//System.out.println(value2);

try {
	fin1 = new FileOutputStream(file);
} catch (FileNotFoundException e1) {
	// TODO Auto-generated catch block
	
	e1.printStackTrace();
}
    

	for(int i=0;i<nrow1;i++)
    {
   
   String a =jTable1.getValueAt(i, 0).toString(); 
   System.out.println(a);    
    char a1[] = a.toCharArray();
        int m=0;
        while(m<a1.length)
           {try{System.out.print(a1[m]);
           
            fin1.write(a1[m++]);
        
           }catch(Exception e)
           {    System.out.println(e);
           }}
        System.out.println("");
        
        try {
			fin1.write(9);
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
    String b =jTable1.getValueAt(i, 1).toString();
    System.out.println(b);    
    char b1[] = b.toCharArray();
        int n=0;
        while(n<b1.length)
           {try{System.out.print(b1[n]);
            fin1.write(b1[n++]);
        
           }catch(Exception e)
           {    System.out.println(e);
           }}
       System.out.println("");
   char ent = '\n';
       try {
    	   //fin1.write((int)ent);
    	  
   
    	   fin1.write(13);
		fin1.write(10);
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    }
}

public void new1 ()
{ 
	String a1 = "data/new/param.txt";
settab(jTable1,a1,2);
	}

public void settab(JTable jtab,String a,int c) {
    
	datamast da = new datamast(a);
     int k = 0;
     int m = 0, n = 0;
     JTable jtab1 = jtab;

    jtab1.setShowVerticalLines(true);
    jtab1.setGridColor(Color.BLACK);
    int nrow = da.j1+1;
    //System.out.println(nrow);
     nrow=nrow/c;
     nrow1=nrow;
	  for(m=0;m<nrow;m++)
	        for(n=0;n<c;n++)
	        { String a1 = da.d1[k++];
	         jtab1.setValueAt(a1,m,n);
	            }
}

TableModelListener tbm ;
public fr2() {
        initComponents();
      this.setVisible(true);
      
      
      jTable1.getModel().addTableModelListener(tbm=new TableModelListener() {

          public void tableChanged(TableModelEvent e) {
             //System.out.println(e);
             int col=e.getColumn();
             int row = e.getFirstRow();
             System.out.println(jTable1.getValueAt(row,col));
          }
        });
        this.setLocationRelativeTo(null);
        new1();        
}
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

	
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
 
   private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Properties", "Values"
            }
        ){
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
       // jTable1.getColumnModel().getColumn(0).
        jButton1.setText("Save File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("close window");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
this.setVisible(false);        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
jTable1.getModel().addTableModelListener(jTable1);
//jTable1.();
jTable1.getModel().addTableModelListener(tbm=new TableModelListener() {

    public void tableChanged(TableModelEvent e) {
       //System.out.println(e);
       int col=e.getColumn();
       int row = e.getFirstRow();
       System.out.println(jTable1.getValueAt(row,col));
    }
  });  
setpara();        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new fr2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration




	
}
